### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by lauraschoebel** [mootcycle/slackporter#5]
This might be completely stupid, but how do I use this tool? There aren't any instructions I can find anywhere.

**Comment by okand** [comment]
It's a node.js application so first you need to have that installed. Varies by platform but it should be installable with a package manager. I installed it just now on my mac with homebrew for example.

Once installed you clone this repo and navigate into the folder. Inside the folder you then run `npm install` to install all the additional dependencies this application needs from the node package manager.

When that is done you run `node index.js` and it should print an IP and port in the terminal for you to visit in your browser.

**Comment by asanakoy** [comment]
run `nodejs index.js` for ubuntu

**Comment by mootcycle** [comment]
My apologies. I'd left this thing fallow for a while. I just fixed a bunch of stuff and it should work again with `node.js` v6+.

**Comment by patelrohan** [comment]
Maybe this should be included in readme file so it is more helpful to someone who does not have coding/scripting experience and stumble upon this by quick Google. :)
