### ISSUE TITLE
Really cool tool, but is not working for me :(

### ISSUE THREAD

**Issue by ceneon** [mootcycle/slackporter#7]
I've been looking for a tool like this for a while.

But it's not working for me... I see all the emojis from the origin slack group just fine:

![image](https://user-images.githubusercontent.com/530965/34571720-fabd3eae-f14d-11e7-83c1-83fb13ca8d93.png)

but when I try to import one, it fails:

![image](https://user-images.githubusercontent.com/530965/34571697-ef9a541c-f14d-11e7-8c42-28ef7a2fbe6d.png)

**Comment by mootcycle** [comment]
Hm. The stack trace doesn't tell me all that much other than a dependency is failing. I just tested a clean install on my machine and it's working fine for me. Any chance you're running an old version of node? I think some of the dependencies require node 8 or higher.

**Comment by wgraham17** [comment]
@ceneon Try disabling 2FA on the target account, worked for me.

**Comment by ceneon** [comment]
Sorry to having left this issue open, I thought I've posted the update. 
It was indeed a node version thing. I updated everything and it worked beautifully!

thanks @mootcycle @wgraham17
